using System;


namespace Exeption
{
    //public class DivZero:Exception
    //{
    //    static public int IntResult(int num, int denom)
    //    {
    //        return (num / denom);
    //    }
    //    static public double DoubleResult(double num, double denom)
    //    {
    //        return (num / denom);
    //    }
    //    static public void Main()
    //    {
    //        // Set an integer equal to 0
    //        int IntVal1 = int.Parse(Console.ReadLine()); ;
    //        // and another not equal to zero
    //        int IntVal2 = 53;
    //        int result = IntVal2 / IntVal1;
    //        try
    //        {
    //            Console.WriteLine("{0} / {1} = {2}", IntVal2, IntVal1, result);
    //        }

    //        catch (DivideByZeroException ex)
    //        {
    //            //   Console.WriteLine(ex.Message);
    //        }
    //        catch (InvalidOperationException ex)
    //        {
    //            Console.Write("Invalid operation. Please try again.");
    //        }
    //        catch (FormatException ex)
    //        {
    //            Console.Write("Not a valid format. Please try again.");
    //        }

    //        // Set a double equal to 0
    //        double dVal1 = 0.0;
    //        double dVal2 = 53.3;
    //        try
    //        {
    //            Console.WriteLine("{0} / {1} = {2}", dVal2, dVal1, DoubleResult(dVal2, dVal1));
    //        }
    //        catch (DivideByZeroException e)
    //        {
    //            Console.WriteLine(e.Message);
    //        }
    //        catch (Exception e)
    //        {
    //            throw e;
    //        }
    //    }


    //  }
         
        
}
